tagslam_parameters:
# optimizer mode: full (full optimization, no iSAM2 used)
#                 slow (use iSAM2, but test for error and use full if error is large)
#                 fast (iSAM2 only, no test for error)
# default: slow
  optimizer_mode: slow
# minimum angle [in degrees] between optical axis and tag surface
  minimum_viewing_angle: 12.0
# number of incremental updates before running
# a full graph optimization (default: 50)
  max_num_incremental_opt: 50
# estimated error of tag corner detector
  pixel_noise: 1.0
# maximum allowed subgraph error. If error is above that,
# the frame is thrown away, the measurement ignored.
  max_subgraph_error: 50.0
# Noise with which the subgraph absolute priors will be
# pinned down. This parameter usually does not need to be touched.
  subgraph_abs_prior_position_noise: 0.1
  subgraph_abs_prior_rotation_noise: 0.1
body_defaults:
  position_noise: 0.05
  rotation_noise: 0.01
default_body: trough
bodies:
 - trough:
     is_static: true
     default_tag_size: 1.0 # height and width of entire tag
     pose:
       position:
         x: -2.65966
         y: -0.239454
         z: 0.499995
       rotation:
         x: 0
         y: 0
         z: 0
       position_noise:
         x: 0.0001
         y: 0.0001
         z: 0.0001
       rotation_noise:
         x: 1.0e-05
         y: 1.0e-05
         z: 1.0e-05
     type: simple
     tags:
     - id: 0
       size: 1.0
       pose:
         position:
           x: 0.76493
           y: -0.272135
           z: 0.676985
         rotation:
           x: 0
           y: 1.57
           z: 0
         position_noise:
           x: 0.0001
           y: 0.0001
           z: 0.0001
         rotation_noise:
           x: 1.0e-05
           y: 1.0e-05
           z: 1.0e-05
     - id: 1
       size: 1.0
       pose:
        position:
          x: 0.55482
          y: 0.732282
          z: -0.012108
        rotation:
          x: 0
          y: 1.56195
          z: 0
        position_noise:
          x: 0.0001
          y: 0.0001
          z: 0.0001
        rotation_noise:
          x: 1.0e-05
          y: 1.0e-05
          z: 1.0e-05
    # Seems to work best when only two tags are predefined
    #  - id: 10
    #    size: 0.1651
    #    pose:
    #     position:
    #       x: 0.5842
    #       y: -0.3302
    #       z: 0.05
    #     rotation:
    #       x: 0
    #       y: 0
    #       z: 0
    #     position_noise:
    #       x: 0.0001
    #       y: 0.0001
    #       z: 0.0001
    #     rotation_noise:
    #       x: 1.0e-05
    #       y: 1.0e-05
    #       z: 1.0e-05
 - rig:
     is_static: false
     type: simple